"""add post likes

Revision ID: a461071145c8
Revises: 6dc653b48f52
Create Date: 2026-05-15 17:02:06.049500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a461071145c8'
down_revision = '6dc653b48f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='unique_post_like')
    )
    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_like_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_like_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_like_post_id'))

    op.drop_table('post_like')
    # ### end Alembic commands ###
